### ISSUE TITLE
Defining enums

### ISSUE THREAD

**Issue by apohllo** [SpencerPark/IJava#39] opened 2018-10-11 11:26 UTC
Is there any way to define enums?
Trying:

```java
enum SpeedUnit {
    MS,
    KMH
}
```

gives 

```
enum types must not be local
 enum SpeedUnit {
 ^     
```

**Comment by SpencerPark** [comment] 2018-10-11 14:43
Hello @apohllo, I was not able to reproduce the error. Running a cell with just the enum definition worked fine.

Could you please show the "Current kernel information" from the notebook's `Help` > `About` section as well as the entire cell you are running?

Because of the format of the error message I am inclined to think you are running this in `jshell` and not actually the jupyter kernel. Likewise this error is probably the result of trying to define the enum within a method which is not allowed in Java making me think there is more to the code you are evaluating than being shown.

**Comment by apohllo** [comment] 2018-10-11 20:04
That's the only contents I am trying to run.
The kernel info is as follows:
```
BeakerX 1.1.0
Java 1.8.0_152-release
hash b65aa83
build time 2018-08-30 17:48 EDT
```

**Comment by apohllo** [comment] 2018-10-11 20:14
I guess the problem comes from the beakrx distribution. The notebook is run in env. where `java -version` gives 9, while I see 1.8 in the kernel information.

**Comment by SpencerPark** [comment] 2018-10-11 20:41
As yes that is the problem, its a different kernel. `BeakerX` is another project that supports running java (among many other jvm languages). If I understand their java interpreter is slightly more limited. This is likely a bug they should be notified of.

I'm closing this issue as it is not related to this project.

**Closed by SpencerPark** 2018-10-11 20:41 UTC

**Comment by apohllo** [comment] 2018-10-15 19:20
I confirm that enums worki in your kernel! Sorry for the mess ;-)
