### ISSUE TITLE
Maybe incompatible with zh_cn locale

### ISSUE THREAD

**Issue by tqjason** [SpencerPark/IJava#28] opened 2018-09-10 02:09 UTC
My test enviroment :
- IJava 1.1.2
- jupyter 4.4.0
- Windows 10 x64
- windows language is CHS
---
There are right error hint in Chinese in jshell.
![exception2](https://user-images.githubusercontent.com/37337136/45272720-7ea23100-b4e1-11e8-9043-9af998f35e82.png)

but it throw exception in jupyter
![exception1](https://user-images.githubusercontent.com/37337136/45272719-7ea23100-b4e1-11e8-8513-c1b67db0b279.png)

**Comment by SpencerPark** [comment] 2018-09-11 18:56
I just gave this a try on a linux and it seems to be working fine, the error messages that were propagated from jshell displayed properly.

The only thing that might be different with windows is the default encoding. Could you try the following steps to see if that fixes the issue, and if it does I will try to get that default into the software so it doesn't require external configuration.

*   search the output of `jupyter kernelspec list` for the location of the `java` kernel
*   in that folder edit the `kernel.json`
```diff
{
    "argv": [
        "java",
+        "-Dfile.encoding=utf8",
        "-jar",
        "/path/to/ijava-1.1.2.jar",
        "{connection_file}"
    ],
...
}
    ```

**Comment by tqjason** [comment] 2018-09-12 04:29
It's working.

Thanks.

**Comment by CSchoel** [comment] 2018-09-18 14:04
I would also be very happy, if this line was in the default `kernel.json`. I used the IJava-Kernel for a bridging course in programming in Germany. My students would regularly add german umlauts to variable names and then wonder why their program does not compile and does not even produce an error message.

**Comment by SpencerPark** [comment] 2018-09-29 22:46
Hello @tqjason and @CSchoel, I believe this issue is fixed upstream now. Would either of you mind testing the kernel from master here and confirm?

The `-Dfile.encoding=utf8` should no longer be necessary. I was able to execute

```java
System.out.println("\u6F22漢字");
String 漢 = "test漢";
漢
```

I am not sure of what the characters are, just copied from wikipedia :) It used to cause the same issue originally referenced but that seems to be fixed now.

Thanks in advance!

**Comment by CSchoel** [comment] 2018-10-04 13:48
Hey, I just compiled and tested the current version of the kernel. The following example code ran without errors:

```java
int xöß€ = 7 + 4;
System.out.println("x = "+xöß€);
```

I also tested your Chinese example and it worked fine. I think the issue is resolved. Thank you very much. :smiley:

**Comment by SpencerPark** [comment] 2018-10-04 15:44
Fantastic, thanks @CSchoel!

**Closed by SpencerPark** 2018-10-04 15:44 UTC
Labels: bug, category: base-kernel
